export type Language = 'ru' | 'en';

export const translations = {
  ru: {
    // HomeScreen
    error: 'Ошибка',
    success: 'Успех',
    appTitle: 'Muffin AI',
    privateMemory: 'Приватная память финансов',
    totalLiquidAssets: 'Всего ликвидных активов',
    liveRates: '🔄 Курсы онлайн',
    updatingRates: '🔄 Обновление...',
    ratesUpdated: 'Курсы обновлены',
    goalTitle: 'Цель',
    setSavingGoal: '🎯 Установить цель сбережений',
    noActiveGoal: 'Нет активных целей сбережений.',
    ruleWarnings: 'Предупреждения правил',
    hackathonLogs: 'Логи проверки хакатона',
    hackathonLogsDesc: 'Экспорт структурированных логов производительности (загрузка модели, TTFT, ток/сек) для судей хакатона.',
    exportLogs: '📤 Экспорт логов аудита',
    clear: 'Очистить',
    askMuffin: 'Спросить Muffin AI',
    viewAccounts: 'Счета и балансы',
    languageLabel: 'Язык / Language',
    confirmClearLogsTitle: 'Подтвердите очистку',
    confirmClearLogsDesc: 'Вы уверены, что хотите удалить все локальные логи производительности?',
    logsCleared: 'Логи производительности очищены.',
    noLogsTitle: 'Нет логов',
    noLogsDesc: 'На устройстве еще нет сохраненных логов работы AI. Начните чат с Muffin AI, чтобы сгенерировать их!',

    // Goal Modal
    editSavingGoal: 'Редактировать цель сбережений',
    savingGoal: 'Цель сбережений',
    goalNameLabel: 'Название / описание цели',
    goalNamePlaceholder: 'например: Купить Теслу, Ликвидные активы',
    targetAmountLabel: 'Целевая сумма ($ USD)',
    targetAmountPlaceholder: 'например: 100000',
    cancel: 'Отмена',
    save: 'Сохранить',
    validationGoalTitle: 'Ошибка валидации',
    validationGoalDesc: 'Пожалуйста, введите корректное положительное число для целевой суммы.',
    saveGoalError: 'Не удалось сохранить цель сбережений.',

    // AccountsScreen
    addWallet: '➕ Добавить кошелек',
    connectBybit: '➕ Подключить Bybit',
    connectedAccounts: 'Подключенные счета',
    syncAll: '🔄 Синхронизировать все',
    tapToViewHistory: 'Нажмите, чтобы посмотреть историю',
    sourceLabel: 'Источник',
    historyTitle: 'История изменений баланса',
    close: 'Закрыть',
    deleteButton: '🗑️ Удалить',
    editAddress: 'Редактировать адрес',
    publicAddressLabel: 'Публичный адрес',
    publicAddressPlaceholder: 'Введите адрес кошелька',
    saveAddressError: 'Не удалось сохранить адрес в базу данных.',
    createWalletError: 'Не удалось создать новый счет кошелька.',
    deleteConnectionTitle: 'Удалить подключение',
    deleteConnectionDesc: 'Вы уверены, что хотите удалить подключение {name}? Это удалит все локальные ключи и историю балансов.',
    deletedTitle: 'Удалено',
    deletedDesc: 'Подключение успешно удалено.',
    deleteError: 'Не удалось удалить подключение.',
    syncSuccess: 'Синхронизация выполнена успешно.',
    syncSingleSuccess: 'Баланс счета успешно обновлен.',
    syncError: 'Ошибка синхронизации',
    syncErrorDesc: 'Не удалось синхронизировать баланс счета.',
    bybitSuccess: 'Подключение к Bybit добавлено и синхронизировано успешно!',
    exchangeApi: 'Exchange API',
    bybitApiLabel: 'Bybit V5 API',

    // Add Wallet Modal
    newWalletNameLabel: 'Название кошелька',
    newWalletNamePlaceholder: 'например: Мой Solana кошелек',
    walletNetworkLabel: 'Сеть кошелька',
    walletAddressLabel: 'Публичный адрес кошелька',
    walletAddressPlaceholder: 'например: 0x... или Solana адрес',

    // Connect Exchange Modal
    exchangeLabel: 'Название подключения',
    exchangePlaceholder: 'например: Мой основной аккаунт',
    apiKeyLabel: 'API Key',
    apiSecretLabel: 'API Secret',
    testnetLabel: 'Использовать Testnet (демо-сеть)',
    testingConnection: 'Тестирование...',
    connectButton: 'Подключить аккаунт',
    validationExchangeDesc: 'Пожалуйста, заполните все поля.',
    exchangeConnError: 'Ошибка подключения',
    exchangeConnErrorDesc: 'Не удалось проверить или сохранить подключение к Bybit. Проверьте ключи API и интернет-соединение.',

    // ChatScreen
    chatWelcome: 'Привет! Я Muffin, твой приватный финансовый ассистент. 🏦\n\nВы можете загрузить скриншот приложения банка или криптокошелька через 📎. Все данные обрабатываются локально.\n\nВы также можете давать мне голосовые или текстовые команды. Вот стандартные форматы:\n• Установка баланса: "На Bybit пятьсот долларов" или "Баланс Kaspi Gold теперь 50000 тенге"\n• Списание: "Потратил 1500 рублей с Bybit Card" или "Минус 20 долларов с наличных"\n• Пополнение: "Добавь 5000 тенге на Kaspi Gold" или "Плюс 100 долларов"\n• Цели: "Хочу накопить 5000 долларов" или "Сколько осталось до цели?"',
    processingScreenshot: '🔍 Обработка скриншота (OCR + Локальный AI-парсинг)...',
    foundBalanceScreenshot: 'Найден баланс на скриншоте:\n🏦 Банк: {bank}\n💰 Баланс: {amount} {currency}',
    savedBalanceSqlite: 'Сохранено в SQLite:\n🏦 Банк: {bank}\n💰 Баланс: {amount} {currency}\nЭквивалент: ${usd}',
    assignToAccount: 'Привязать к счету:',
    orEnterNewAccountName: 'Или введите новое имя счета:',
    saveBalanceButton: 'Сохранить баланс',
    permissionRequired: 'Требуется разрешение',
    cameraPermissionDesc: 'Разрешение камеры необходимо для создания снимка.',
    photoPermissionDesc: 'Разрешение к галерее необходимо для выбора скриншота.',
    ocrExtractError: 'Не удалось извлечь название банка или сумму со скриншота. Пожалуйста, попробуйте еще раз с более четким изображением.',
    ocrModelError: 'Ошибка при обработке скриншота. Убедитесь, что модель OCR полностью загружена.',
    confirmOcrUpdatePrompt: 'Я обновил баланс счета {bank} до {amount} {currency}.',
    aiCalculating: '📊 Muffin считает...',
    aiThinking: '💭 Ход мыслей:',
    askMuffinPlaceholder: 'Спроси Muffin AI...',
    listeningPlaceholder: 'Слушаю... Говорите!',
    modelDownloading: 'Скачивание модели AI ({progress}%)...\nПожалуйста, подождите, это займет время (около 2.1 ГБ).',
    modelInitializing: 'Инициализация модели AI...\nЗагрузка весов в память устройства, пожалуйста, подождите.',
    speechModelDownloading: 'Скачивание модели речи ({progress}%)... Около 147 МБ',
    speechModelInitializing: 'Инициализация модели речи...\nЗагрузка весов в память устройства, пожалуйста, подождите.',
    transcribingVoice: '🗣️ Транскрипция голосовой команды...',
    fetchingBtcPrice: 'Запрос цены Bitcoin в реальном времени...',
    processingAction: 'Обработка команды...',
    cryptoQuery: '🌐 Запрос Крипто',
    goalUpdate: '🎯 Обновление Цели',
    balanceAction: '⚙️ Действие с Балансом',
    toolAddBalance: 'Добавить {amount} {currency} на счет {accountName}',
    toolSubtractBalance: 'Списать {amount} {currency} со счета {accountName}',
    toolSetBalance: 'Установить баланс счета {accountName} в размере {amount} {currency}',
    toolUpdateGoal: 'Установить цель сбережений: "{title}" на сумму ${targetValue}',
    actionCancelled: 'Действие отменено: {action}',
    cancelledSavingBalance: '❌ Сохранение баланса отменено.',
    whisperSetupError: 'Не удалось настроить локальную модель распознавания речи.',
    micPermissionDesc: 'Разрешение на доступ к микрофону требуется для записи голосовых команд.',
    startRecordingError: 'Не удалось начать запись звука.',
    stopRecordingError: 'Не удалось остановить запись звука.',
    noSpeechTitle: 'Речь не обнаружена',
    noSpeechDesc: 'Модель не распознала речь. Попробуйте говорить ближе к микрофону.',
    transcriptionErrorTitle: 'Ошибка распознавания',
    transcriptionErrorDesc: 'Не удалось локально расшифровать аудиозапись.',
    addScreenshotTitle: 'Добавить скриншот банка',
    addScreenshotDesc: 'Выберите способ добавления скриншота вашего банка или кошелька',
    takePhotoCamera: 'Сделать снимок / Камера',
    chooseFromLibrary: 'Выбрать из галереи',
    dbErrorTitle: 'Ошибка базы данных',
    dbSaveBalanceError: 'Не удалось сохранить баланс в базу данных SQLite.',
    ocrAccountPlaceholder: 'Название счета (например, OKX, Kaspi)',
    aiConnectError: 'Извините, возникла проблема с подключением к AI.',
    aiCancelConfirmError: 'Извините, возникла проблема с подтверждением отмены.',
    aiOcrSaveConfirmError: 'Извините, возникла проблема с подтверждением сохранения баланса.',
    executingInSeconds: 'Выполнение через {seconds}с...',
    runningAction: 'Выполнение...',
    completedAction: '✓ Выполнено',
    cancelledAction: '✗ Отменено',
    setOp: 'Установить',
    addOp: 'Добавить',
    spendOp: 'Списать',
    confirmButton: 'Подтвердить',
    amountLabel: 'Сумма',
    accountLabel: 'Счет',
    operationLabel: 'Операция',
    toolBalanceIntro: 'Я распознал команду для изменения баланса. Пожалуйста, проверьте и подтвердите детали:',
    toolGoalIntro: 'Я распознал команду для изменения цели. Пожалуйста, проверьте и подтвердите детали:',
  },
  en: {
    // HomeScreen
    error: 'Error',
    success: 'Success',
    appTitle: 'Muffin AI',
    privateMemory: 'Private Financial Memory',
    totalLiquidAssets: 'Total liquid assets',
    liveRates: '🔄 Live Rates',
    updatingRates: '🔄 Updating...',
    ratesUpdated: 'Rates updated',
    goalTitle: 'Goal',
    setSavingGoal: '🎯 Set Saving Goal',
    noActiveGoal: 'No active savings goal set.',
    ruleWarnings: 'Rule Warnings',
    hackathonLogs: 'Hackathon Verification Logs',
    hackathonLogsDesc: 'Export structured performance logs (model loading, TTFT, tok/sec) for the QVAC judges.',
    exportLogs: '📤 Export Audit Logs',
    clear: 'Clear',
    askMuffin: 'Ask Muffin AI',
    viewAccounts: 'View Accounts',
    languageLabel: 'Language / Язык',
    confirmClearLogsTitle: 'Confirm Clear',
    confirmClearLogsDesc: 'Are you sure you want to delete all local performance logs?',
    logsCleared: 'Performance logs have been cleared.',
    noLogsTitle: 'No Logs',
    noLogsDesc: 'There are no inference or model load logs captured on this device yet. Start a chat with Muffin AI to generate logs!',

    // Goal Modal
    editSavingGoal: 'Edit Saving Goal',
    savingGoal: 'Saving Goal',
    goalNameLabel: 'Goal Name / Title',
    goalNamePlaceholder: 'e.g. Buy a Tesla, Liquid Assets Target',
    targetAmountLabel: 'Target Amount ($ USD)',
    targetAmountPlaceholder: 'e.g. 100000',
    cancel: 'Cancel',
    save: 'Save',
    validationGoalTitle: 'Validation Error',
    validationGoalDesc: 'Please enter a valid positive number for the target amount.',
    saveGoalError: 'Failed to update saving goal.',

    // AccountsScreen
    addWallet: '➕ Add Wallet',
    connectBybit: '➕ Connect Bybit',
    connectedAccounts: 'Connected Accounts',
    syncAll: '🔄 Sync All',
    tapToViewHistory: 'Tap to view history',
    sourceLabel: 'Source',
    historyTitle: 'Balance History Logs',
    close: 'Close',
    deleteButton: '🗑️ Delete',
    editAddress: 'Edit Address',
    publicAddressLabel: 'Public Address',
    publicAddressPlaceholder: 'Enter wallet public address',
    saveAddressError: 'Failed to save address to database.',
    createWalletError: 'Failed to create new wallet account.',
    deleteConnectionTitle: 'Delete Connection',
    deleteConnectionDesc: 'Are you sure you want to delete connection {name}? This will remove all local credentials and snapshots.',
    deletedTitle: 'Deleted',
    deletedDesc: 'Connection deleted successfully.',
    deleteError: 'Failed to delete connection.',
    syncSuccess: 'All balances updated successfully.',
    syncSingleSuccess: 'Account balance updated successfully.',
    syncError: 'Sync Error',
    syncErrorDesc: 'Failed to sync account balance.',
    bybitSuccess: 'Bybit connection added and synchronized successfully!',
    exchangeApi: 'Exchange API',
    bybitApiLabel: 'Bybit V5 API',

    // Add Wallet Modal
    newWalletNameLabel: 'Wallet Name',
    newWalletNamePlaceholder: 'e.g. My Solana Wallet',
    walletNetworkLabel: 'Wallet Network',
    walletAddressLabel: 'Public Address',
    walletAddressPlaceholder: 'e.g. 0x... or Solana address',

    // Connect Exchange Modal
    exchangeLabel: 'Connection Name / Label',
    exchangePlaceholder: 'e.g. My Primary Account',
    apiKeyLabel: 'API Key',
    apiSecretLabel: 'API Secret',
    testnetLabel: 'Use Testnet (demo environment)',
    testingConnection: 'Testing...',
    connectButton: 'Connect Account',
    validationExchangeDesc: 'Please fill in all fields.',
    exchangeConnError: 'Connection Error',
    exchangeConnErrorDesc: 'Failed to test or save Bybit connection. Check your keys and internet connection.',

    // ChatScreen
    chatWelcome: 'Hi! I am Muffin, your private financial assistant. 🏦\n\nYou can upload a screenshot of any bank app or crypto wallet using 📎. All OCR data is processed locally.\n\nYou can also speak or type commands. Here are the standard formats:\n• Set balance: "On Bybit five hundred dollars" or "My Kaspi Gold balance is now 50000 KZT"\n• Spend: "Spent 1500 RUB from Bybit Card" or "Minus 20 dollars from Cash"\n• Add: "Add 5000 KZT to Kaspi Gold" or "Plus 100 dollars"\n• Goals: "Set savings goal to 5000 USD" or "How much is left until my goal?"',
    processingScreenshot: '🔍 Processing screenshot (OCR + Local AI parsing)...',
    foundBalanceScreenshot: 'Found balance in screenshot:\n🏦 Bank: {bank}\n💰 Balance: {amount} {currency}',
    savedBalanceSqlite: 'Saved balance to SQLite:\n🏦 Bank: {bank}\n💰 Balance: {amount} {currency}\nEquivalent: ${usd}',
    assignToAccount: 'Assign to account:',
    orEnterNewAccountName: 'Or enter a new account name:',
    saveBalanceButton: 'Save Balance',
    permissionRequired: 'Permission Required',
    cameraPermissionDesc: 'Camera permission is required to take a screenshot photo.',
    photoPermissionDesc: 'Photo library permission is required to select a screenshot.',
    ocrExtractError: 'Could not extract bank name or balance from the screenshot. Please try again with a clearer image.',
    ocrModelError: 'Error processing the screenshot. Make sure the OCR model is fully loaded.',
    confirmOcrUpdatePrompt: 'I just updated my {bank} balance to {amount} {currency}.',
    aiCalculating: '📊 Muffin is calculating...',
    aiThinking: '💭 Thought Process:',
    askMuffinPlaceholder: 'Ask Muffin AI...',
    listeningPlaceholder: 'Listening... Speak now!',
    modelDownloading: 'Downloading AI Model ({progress}%)...\nPlease wait, this will take a while (approx 2.1GB).',
    modelInitializing: 'Initializing AI Model...\nLoading model weights into memory, please wait.',
    speechModelDownloading: 'Downloading Speech Model ({progress}%)... Approx 147MB',
    speechModelInitializing: 'Initializing Speech Model...\nLoading model weights into memory, please wait.',
    transcribingVoice: '🗣️ Transcribing voice command...',
    fetchingBtcPrice: 'Fetching real-time Bitcoin price...',
    processingAction: 'Processing command...',
    cryptoQuery: '🌐 Crypto Query',
    goalUpdate: '🎯 Goal Update',
    balanceAction: '⚙️ Balance Action',
    toolAddBalance: 'Add {amount} {currency} to {accountName}',
    toolSubtractBalance: 'Spend {amount} {currency} from {accountName}',
    toolSetBalance: 'Set balance of {accountName} to {amount} {currency}',
    toolUpdateGoal: 'Set savings goal: "{title}" to ${targetValue}',
    actionCancelled: 'Action cancelled: {action}',
    cancelledSavingBalance: '❌ Cancelled saving balance.',
    whisperSetupError: 'Failed to setup local speech recognition model.',
    micPermissionDesc: 'Microphone permission is required to record voice commands.',
    startRecordingError: 'Failed to start audio recording.',
    stopRecordingError: 'Failed to stop audio recording.',
    noSpeechTitle: 'No Speech Detected',
    noSpeechDesc: 'Whisper could not hear any speech. Please try speaking closer to the microphone.',
    transcriptionErrorTitle: 'Transcription Error',
    transcriptionErrorDesc: 'Failed to transcribe audio locally.',
    addScreenshotTitle: 'Add Bank Screenshot',
    addScreenshotDesc: 'Choose how to add your bank screenshot',
    takePhotoCamera: 'Take Photo / Camera',
    chooseFromLibrary: 'Choose from Library',
    dbErrorTitle: 'Database Error',
    dbSaveBalanceError: 'Failed to save balance to SQLite database.',
    ocrAccountPlaceholder: 'Account name (e.g. OKX, Kaspi)',
    aiConnectError: 'Sorry, I had an issue connecting to the AI.',
    aiCancelConfirmError: 'Sorry, I had an issue executing the cancellation confirmation.',
    aiOcrSaveConfirmError: 'Sorry, I had an issue updating after saving balance.',
    executingInSeconds: 'Executing in {seconds}s...',
    runningAction: 'Running action...',
    completedAction: '✓ Completed',
    cancelledAction: '✗ Cancelled',
    setOp: 'Set',
    addOp: 'Add',
    spendOp: 'Spend',
    confirmButton: 'Confirm',
    amountLabel: 'Amount',
    accountLabel: 'Account',
    operationLabel: 'Operation',
    toolBalanceIntro: 'I recognized a balance update command. Please review and confirm the details:',
    toolGoalIntro: 'I recognized a goal update command. Please review and confirm the details:',
  }
};

export function t(key: keyof typeof translations['en'], lang: Language, params?: Record<string, string | number>): string {
  const dict = translations[lang] || translations['en'];
  let text = dict[key] || translations['en'][key] || String(key);
  if (params) {
    Object.keys(params).forEach(p => {
      text = text.replace(`{${p}}`, String(params[p]));
    });
  }
  return text;
}
